
spring:
  application:
    name: AI-Powered Task Management Portal

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    refresh-token-expiration: 604800000
logging:
  level:
    root: INFO
    com.ai.taskportal: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG